Repository kami-blue/bot-kt, pull requests merged in 2020-11, with the labels that each got.

#73 [cleanup] Cleaned up CapeUser.editCapes()
  src/main/kotlin/commands/CapeCommand.kt
Labels: -module, enhancement

#72 [feature] Added DiscordUserArgumentType
  src/main/kotlin/BrigadierDsl.kt
  src/main/kotlin/Command.kt
  src/main/kotlin/Main.kt
  src/main/kotlin/helpers/DiscordUserArgumentType.kt
  src/main/kotlin/helpers/StringHelper.kt
Labels: --review-pending, -module, -other, enhancement, good-first-issue

#83 [refactor] Update kotlin
  gradle.properties
  src/main/kotlin/commands/BanCommand.kt
  src/main/kotlin/util.kt
Labels: --review-pending, -dependencies, enhancement
