Repository kami-blue/bot-kt, pull requests merged in 2020-12, with the labels that each got.

#97 [feature] ;say command / removal of announce command
  src/main/kotlin/BrigadierDsl.kt
  src/main/kotlin/ConfigTypes.kt
  src/main/kotlin/Permissions.kt
  src/main/kotlin/arguments/DiscordChannelArgumentType.kt
  src/main/kotlin/arguments/DiscordEmojiArgumentType.kt
  src/main/kotlin/arguments/DiscordUserArgumentType.kt
  src/main/kotlin/commands/AnnounceCommand.kt
  src/main/kotlin/commands/SayCommand.kt
  src/main/kotlin/utils/Exceptions.kt
Labels: --review-pending, enhancement, new

#351 [feature] Added Logger
  .run/Main.run.xml
  build.gradle
  gradle.properties
  src/main/kotlin/org/kamiblue/botkt/Bot.kt
  src/main/kotlin/org/kamiblue/botkt/Main.kt
  src/main/kotlin/org/kamiblue/botkt/command/CommandManager.kt
  src/main/kotlin/org/kamiblue/botkt/command/commands/info/TicketCommand.kt
  src/main/kotlin/org/kamiblue/botkt/command/commands/misc/CapeCommand.kt
  src/main/kotlin/org/kamiblue/botkt/command/commands/moderation/MuteCommand.kt
  src/main/kotlin/org/kamiblue/botkt/command/commands/system/ExceptionCommand.kt
  src/main/kotlin/org/kamiblue/botkt/event/BotEventBus.kt
  src/main/kotlin/org/kamiblue/botkt/helpers/UpdateHelper.kt
  src/main/kotlin/org/kamiblue/botkt/manager/ManagerLoader.kt
  src/main/kotlin/org/kamiblue/botkt/manager/managers/ConfigManager.kt
  src/main/kotlin/org/kamiblue/botkt/utils/GitHubUtils.kt
  src/main/kotlin/org/kamiblue/botkt/utils/MessageSendUtils.kt
  src/main/kotlin/org/kamiblue/botkt/utils/util.kt
  src/main/resources/log4j2.xml
Labels: -dependencies, new

#352 [new] Shutdown event
  src/main/kotlin/org/kamiblue/botkt/Main.kt
  src/main/kotlin/org/kamiblue/botkt/command/CommandManager.kt
  src/main/kotlin/org/kamiblue/botkt/command/commands/github/IssueCommand.kt
  src/main/kotlin/org/kamiblue/botkt/command/commands/info/TicketCommand.kt
  src/main/kotlin/org/kamiblue/botkt/command/commands/misc/CapeCommand.kt
  src/main/kotlin/org/kamiblue/botkt/event/events/ShutdownEvent.kt
  src/main/kotlin/org/kamiblue/botkt/manager/managers/MuteManager.kt
Labels: new

#353 [refactor] Coroutines
  src/main/kotlin/org/kamiblue/botkt/BackgroundScope.kt
  src/main/kotlin/org/kamiblue/botkt/Bot.kt
  src/main/kotlin/org/kamiblue/botkt/Main.kt
  src/main/kotlin/org/kamiblue/botkt/command/CommandManager.kt
  src/main/kotlin/org/kamiblue/botkt/command/commands/github/CounterCommand.kt
  src/main/kotlin/org/kamiblue/botkt/command/commands/misc/CapeCommand.kt
  src/main/kotlin/org/kamiblue/botkt/event/BotEventBus.kt
  src/main/kotlin/org/kamiblue/botkt/manager/managers/MuteManager.kt
Labels: --review-pending, -other

#354 [new] Console Command System
  src/main/kotlin/org/kamiblue/botkt/Console.kt
  src/main/kotlin/org/kamiblue/botkt/Main.kt
  src/main/kotlin/org/kamiblue/botkt/Permissions.kt
  src/main/kotlin/org/kamiblue/botkt/command/BotCommand.kt
  src/main/kotlin/org/kamiblue/botkt/command/CommandManager.kt
  src/main/kotlin/org/kamiblue/botkt/command/commands/github/IssueCommand.kt
  src/main/kotlin/org/kamiblue/botkt/command/commands/info/TicketCommand.kt
  src/main/kotlin/org/kamiblue/botkt/command/commands/moderation/BanCommand.kt
  src/main/kotlin/org/kamiblue/botkt/command/commands/moderation/MuteCommand.kt
  src/main/kotlin/org/kamiblue/botkt/command/commands/moderation/PurgeCommand.kt
Labels: --review-pending, new

#355 [cleanup] Utils and Http requests
  build.gradle
  src/main/kotlin/org/kamiblue/botkt/Main.kt
  src/main/kotlin/org/kamiblue/botkt/command/BotCommand.kt
  src/main/kotlin/org/kamiblue/botkt/command/arguments/Args.kt
  src/main/kotlin/org/kamiblue/botkt/command/commands/fun/StealEmojiCommand.kt
  src/main/kotlin/org/kamiblue/botkt/command/commands/github/CounterCommand.kt
  src/main/kotlin/org/kamiblue/botkt/command/commands/github/IssueCommand.kt
  src/main/kotlin/org/kamiblue/botkt/command/commands/info/HelpCommand.kt
  src/main/kotlin/org/kamiblue/botkt/command/commands/info/RoleInfoCommand.kt
  src/main/kotlin/org/kamiblue/botkt/command/commands/info/TicketCommand.kt
  src/main/kotlin/org/kamiblue/botkt/command/commands/info/UserInfoCommand.kt
  src/main/kotlin/org/kamiblue/botkt/command/commands/misc/CapeCommand.kt
  src/main/kotlin/org/kamiblue/botkt/command/commands/moderation/BanCommand.kt
  src/main/kotlin/org/kamiblue/botkt/command/commands/moderation/ChannelCommand.kt
  src/main/kotlin/org/kamiblue/botkt/command/commands/moderation/MuteCommand.kt
  src/main/kotlin/org/kamiblue/botkt/command/commands/moderation/PurgeCommand.kt
  src/main/kotlin/org/kamiblue/botkt/command/commands/moderation/TopicCommand.kt
  src/main/kotlin/org/kamiblue/botkt/command/commands/moderation/UnmuteCommand.kt
  src/main/kotlin/org/kamiblue/botkt/command/commands/system/ConfigCommand.kt
  src/main/kotlin/org/kamiblue/botkt/command/commands/system/ExceptionCommand.kt
  src/main/kotlin/org/kamiblue/botkt/command/commands/system/SayCommand.kt
  src/main/kotlin/org/kamiblue/botkt/entity/Emoji.kt
  src/main/kotlin/org/kamiblue/botkt/entity/Reaction.kt
  src/main/kotlin/org/kamiblue/botkt/manager/managers/JoinLeaveManager.kt
  src/main/kotlin/org/kamiblue/botkt/utils/GitHubUtils.kt
  src/main/kotlin/org/kamiblue/botkt/utils/MessageSendUtils.kt
  src/main/kotlin/org/kamiblue/botkt/utils/MessageUtils.kt
  src/main/kotlin/org/kamiblue/botkt/utils/ReactionUtils.kt
  src/main/kotlin/org/kamiblue/botkt/utils/SnowflakeHelper.kt
  src/main/kotlin/org/kamiblue/botkt/utils/StringUtils.kt
  src/main/kotlin/org/kamiblue/botkt/utils/TimeUtils.kt
  src/main/kotlin/org/kamiblue/botkt/utils/UserUtils.kt
  src/main/kotlin/org/kamiblue/botkt/utils/util.kt
Labels: --review-pending, -dependencies, -other, enhancement

#356 [new] Added ;rickroll command
  src/main/kotlin/org/kamiblue/botkt/command/commands/fun/RickRollCommand.kt
Labels: --review-pending, new, server-specific

#361 [new] File upload
  src/main/kotlin/org/kamiblue/botkt/ConfigTypes.kt
  src/main/kotlin/org/kamiblue/botkt/command/commands/fun/RickRollCommand.kt
  src/main/kotlin/org/kamiblue/botkt/command/commands/fun/StealEmojiCommand.kt
  src/main/kotlin/org/kamiblue/botkt/command/commands/github/CounterCommand.kt
  src/main/kotlin/org/kamiblue/botkt/command/commands/github/IssueCommand.kt
  src/main/kotlin/org/kamiblue/botkt/command/commands/info/AvatarInfoCommand.kt
  src/main/kotlin/org/kamiblue/botkt/command/commands/info/HelpCommand.kt
  src/main/kotlin/org/kamiblue/botkt/command/commands/info/RoleInfoCommand.kt
  src/main/kotlin/org/kamiblue/botkt/command/commands/info/TicketCommand.kt
  src/main/kotlin/org/kamiblue/botkt/command/commands/info/UserInfoCommand.kt
  src/main/kotlin/org/kamiblue/botkt/command/commands/misc/CapeCommand.kt
  src/main/kotlin/org/kamiblue/botkt/command/commands/moderation/BanCommand.kt
  src/main/kotlin/org/kamiblue/botkt/command/commands/moderation/ChannelCommand.kt
  src/main/kotlin/org/kamiblue/botkt/command/commands/moderation/MuteCommand.kt
  src/main/kotlin/org/kamiblue/botkt/command/commands/moderation/PurgeCommand.kt
  src/main/kotlin/org/kamiblue/botkt/command/commands/moderation/TopicCommand.kt
  src/main/kotlin/org/kamiblue/botkt/command/commands/moderation/UnmuteCommand.kt
  src/main/kotlin/org/kamiblue/botkt/command/commands/system/ConfigCommand.kt
  src/main/kotlin/org/kamiblue/botkt/command/commands/system/ExceptionCommand.kt
  src/main/kotlin/org/kamiblue/botkt/command/commands/system/SayCommand.kt
  src/main/kotlin/org/kamiblue/botkt/utils/GitHubUtils.kt
  src/main/kotlin/org/kamiblue/botkt/utils/MessageUtils.kt
Labels: --changes-requested, new

#362 [cleanup] Ticket Logging
  src/main/kotlin/org/kamiblue/botkt/command/commands/info/TicketCommand.kt
  src/main/kotlin/org/kamiblue/botkt/utils/MessageUtils.kt
  src/main/kotlin/org/kamiblue/botkt/utils/StringUtils.kt
Labels: --review-pending, enhancement

#358 [new] Added uptime command
  src/main/kotlin/org/kamiblue/botkt/Main.kt
  src/main/kotlin/org/kamiblue/botkt/command/commands/moderation/MuteCommand.kt
  src/main/kotlin/org/kamiblue/botkt/command/commands/system/UptimeCommand.kt
  src/main/kotlin/org/kamiblue/botkt/utils/TimeUtils.kt
Labels: --review-pending, new
