Repository kami-blue/bot-kt, pull requests merged in 2020-10, with the labels that each got.

#45 [new] Issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: --changes-requested, -other, new

#43 [new] Announce command
  src/main/kotlin/ConfigTypes.kt
  src/main/kotlin/Permissions.kt
  src/main/kotlin/commands/AnnounceCommand.kt
Labels: --review-pending, -module, new

#41 [feature] Ban command
  src/main/kotlin/ConfigTypes.kt
  src/main/kotlin/Permissions.kt
  src/main/kotlin/commands/BanCommand.kt
Labels: --review-pending, -module, new

#51 [fix] ;issue colors and ban message
  src/main/kotlin/Main.kt
  src/main/kotlin/commands/BanCommand.kt
  src/main/kotlin/commands/IssueCommand.kt
Labels: --changes-requested, -module

#36 [feature] Docker
  .github/workflows/docker-publish.yml
  .gitmodules
  Dockerfile
  README.md
  scripts/docker-build.sh
  scripts/docker-run.sh
Labels: --testing-pending, -module, new

#38 [feature] Travis CI and Actions CI
  .github/workflows/.travis.yml
  .github/workflows/gradle.yml
  .gitignore
  .travis.yml
  README.md
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: --changes-requested, -building

#55 [feature] `;roleinfo` command
  src/main/kotlin/Send.kt
  src/main/kotlin/commands/ChannelCommand.kt
  src/main/kotlin/commands/RoleInfoCommand.kt
  src/main/kotlin/helpers/StringHelper.kt
  src/main/kotlin/util.kt
Labels: -module, new
